services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    volumes:
      - "./:/app"
    ports:
      - "${API_PORT}:${API_PORT}"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

